export const GET_REGION_SUCCESS = "GET_REGEION_SUCCESS";
export const GET_COUNTRY_SUCCESS = "GET_COUNTRY_SUCCESS";
export const GET_SEGMENT_SUCCESS = "GET_SEGMENT_SUCCESS";
export const GET_INSTRUMENT_SUCCESS = "GET_INSTRUMENT_SUCCESS";
export const GET_EXCHANGE_SUCCESS = "GET_EXCHANGE_SUCCESS";
export const GET_SCRIPT_SUCCESS = "GET_SCRIPT_SUCCESS";
export const EXCHANGE_ERROR = "EXCHANGE_ERROR";
export const GET_ERROR = "GET_ERROR";