export const DISCUSSION_JOIN_SUCCESS= "DISCUSSION_JOIN_SUCCESS";
export const DISCUSSION_JOIN_ERROR= "DISCUSSION_JOIN_ERROR";
export const GET_IDEA_ID_SUCCESS="GET_IDEA_ID_SUCCESS";
export const GET_IDEA_ID_ERROR="GET_IDEA_ID_ERROR";
export const GET_IDEAS_SUCCESS= "GET_IDEAS_SUCCESS";
export const GET_IDEAS_ERROR = "GET_IDEAS_ERROR";
