export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_EMAIL = 'REGISTER_EMAIL';
export const REGISTER_PASSWORD = 'REGISTER_PASSWORD';
export const REGISTER_PHONE = 'REGISTER_PHONE';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';