const IDEA_PREFERENCES_SUCCESS = "IDEA_PREFERENCES_SUCCESS";
const IDEA_PREFERENCES_ERROR = "IDEA_PREFERENCES_ERROR";
const ADVISOR_PREFERENCES_SUCCESS = "ADVISOR_PREFERENCES_SUCCESS";
const ADVISOR_PREFERENCES_ERROR = "ADVISOR_PREFERENCES_ERROR";
const PROFILE_PREFERENCES_SUCCESS = "PROFILE_PREFERENCES_SUCCESS";
const PROFILE_PREFERENCES_ERROR = "PROFILE_PREFERENCES_ERROR";
const PUSH_NOTIFICATION_SUCCESS = "PUSH_NOTIFICATION_SUCCESS";
const PUSH_NOTIFICATION_ERROR = "PUSH_NOTIFICATION_ERROR";
const EMAIL_NOTIFICATION_SUCCESS = "EMAIL_NOTIFICATION_SUCCESS";
const EMAIL_NOTIFICATION_ERROR = "EMAIL_NOTIFICATION_ERROR";
const SMS_NOTIFICATION_SUCCESS = "SMS_NOTIFICATION_SUCCESS";
const SMS_NOTIFICATION_ERROR = "SMS_NOTIFICATION_ERROR";
const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
const GET_NOTIFICATION_ERROR = "GET_NOTIFICATION_ERROR";

export {
    IDEA_PREFERENCES_SUCCESS, IDEA_PREFERENCES_ERROR, ADVISOR_PREFERENCES_SUCCESS, ADVISOR_PREFERENCES_ERROR, PROFILE_PREFERENCES_SUCCESS,
    PROFILE_PREFERENCES_ERROR, PUSH_NOTIFICATION_SUCCESS, PUSH_NOTIFICATION_ERROR, EMAIL_NOTIFICATION_SUCCESS, EMAIL_NOTIFICATION_ERROR,
    SMS_NOTIFICATION_SUCCESS, SMS_NOTIFICATION_ERROR, GET_NOTIFICATION_SUCCESS, GET_NOTIFICATION_ERROR 
}