const GET_WALLET_SUCCESS = 'GetWalletSuccess';
const GET_WALLET_ERROR = 'GetWalletError';
const MONEY_WALLET_ADDED = 'GetWalletAdded';
const GET_TRANSACTION_SUCCESS = 'GET_TRANSACTION_SUCCESS';
const GET_TRANSACTION_ERROR = 'GET_TRANSACTION_ERROR';


export {GET_WALLET_SUCCESS, GET_WALLET_ERROR, MONEY_WALLET_ADDED, GET_TRANSACTION_SUCCESS, GET_TRANSACTION_ERROR };