export let ApiConfig = {
 // HOST: "https://devserver.elsbuly.com:3000",
  // HOST: "https://elsbulyserver.tranzman.com:3000",
   HOST: "http://localhost:3000",
  LOGIN: "/auth/local/",
  REGISTER_USER: "/user",
  RESET: "/",
  CHANGE_PASSWORD: "/",
  REGION: '/api/v1/common/region',
  COUNTRY: '/api/v1/common/country',
  EXCHANGE: '/api/v1/common/exchange',
  INSTRUMENT: '/api/v1/common/instrument',
  SEGMENT: '/api/v1/common/segment',
  SCRIPT: '/api/v1/common/script',
  CREATE_IDEA: "/api/v1/ideas",
  IDEAS_GET: '/api/v1/ideas',
  GET_IDEA: '/api/v1/ideas/',
  DISCUSSION_EXIT: "/",
  CREATE_RATING: '/api/v1/ideas/',
  USER_MENU: '/api/v1/users/menu',
  ADD_WALLET: '/api/v1/wallet/add',
  GET_WALLET: '/api/v1/wallet',
  TRADERSUBSCRIBE: '/api/v1/traders/subscription',
  ADVISORSUBSCRIPTIONS: '/api/v1/traders/subscription',
  ADVISORS: '/api/v1/advisors',
  TRADERSUBSCRIPTIONS: '/api/v1/traders/subscription',
  CANCEL_SUBSCRIPTION: '/api/v1/traders/cancel_subscription/',
  TRADER_SUBSCRIBED_IDEAS: '/api/v1/traders/',
  TRADER_SUBSCRIBED_ALL_IDEAS: '/api/v1/traders/ideas',
  ADDIDEABOARD: '/api/v1/traders/addIdeaBoard',
  GET_IDEA_BOARD_TRADER: '/api/v1/traders/getIdeaBoardTrader',
  IDEABOARDTRADER: '/api/v1/traders/addIdeaBoardTrader',
  DISCUSSIONJOIN: '/api/v1/traders/discussionJoin',
  DISCUSSIONEXIT: '/api/v1/traders/discussionExit',
  GETDISCUSSIONUSER: '/api/v1/traders/discussionUser/',
  MOBILE_OTP: '/api/v1/users/mobile_otp',
  VERIFY_OTP: '/api/v1/users/verify_otp',
  RESEND_OTP: '/api/v1/users/resend_otp',
  SMSOTP: '/api/v1/sms',
  UPDATE_USER: '/api/v1/users/mobile_otp',
  PROFILE_IMAGE: '/api/v1/users/profile-image',
  GET_IMAGE: '/api/v1/users/get_image',
  USER_NOTIFICATION_SUBSCRITION: '/api/v1/communication',
  PREFERENCES: '/api/v1/preferences',
  GET_TRANSACTION: '/api/v1/wallet/get_transaction'
  // SEND_EMAIL:'/api/v1/email',
  // SEND_EMAIL_IDEASINFO:'/api/v1/email/ideas'
}

export let UrlConfig = {
  Ideas: "/idea",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  REGISTER: "/register",
  RATINGS: "/Ratings",
  IDEA_GENERATE: "/idea/Generate",
  DISCUSSION_DETAIL: "discussion/detail/",
  DISCUSSIONEXIT: "/discussion/exit",
  DISCUSSION_JOIN: "discussion/join",
  TRADER: "/trader",
  ADVISORS_LIST: '/trader/advisors_list',
  TRADER_SUBSCRIPTIONS: '/trader/subscriptions',
  TRADER_ADVISOR_IDEAS: '/trader/advisorideas/',
  TRADER_ADVIOSR_ALL_IDEAS: '/trader/ideas',
  REGISTER_PHONE: '/register',
  WALLET: '/wallet',
  PROFILE: '/profile'
}
export let PathConfig = {
  DISCUSSIONS: "/discussion",
  IDEAS: "/idea",
  RATINGS: "/Ratings",
  PREFRENCES: "/preferences",
  MONEY: "",
  PROFILE: "/profile",
  PERFORMANCE: "",
  GENERATE: "/idea/Generate"
}